# This file will be used to connect to a Postgres instance for our Spring boot backend.
version: '3.8'

services:
  db:
    image: "postgres:16.0"
    restart: always
    ports:
      - "5433:5432"
    environment:
      # We might need to use environment variables here:
      POSTGRES_PASSWORD: ${PG_ID}
      POSTGRES_USER: ${PG_PW}
      POSTGRES_DB: swiftyticketing

