# REST test cases

#admin jwt token: 
#user jwt token:  


###
#admin creates an event
POST http://localhost:8080/events/create
Content-Type: application/json
Authorization: Bearer 

{
    "eventName": "concert",
    "artists": ["people", "more people"],
    "dates": ["2001-05-06"],
    "venue": "some stage",
    "venueCapacity": 50
}
###

###
#admin create a zone for event 1
POST http://localhost:8080/events/1/createZone
Content-Type: application/json
Authorization: Bearer 

{
    "zoneCapacity": 1,
    "zoneName": "testZone",
    "zoneDate": "2001-05-06"
}
###


###
#admin creates another zone for event 1
POST http://localhost:8080/events/1/createZone
Content-Type: application/json
Authorization: Bearer 

{
    "zoneCapacity": 10,
    "zoneName": "testZone2",
    "zoneDate": "2001-05-06"
}
###

###
#admin raffles all the zones in event 1.
PUT http://localhost:8080/events/1/raffle
Content-Type: application/json
Authorization: Bearer 

###
#admin creates another event
POST http://localhost:8080/events/create
Content-Type: application/json
Authorization: Bearer 

{
    "eventName": "concert2",
    "artists": ["people", "more people"],
    "dates": ["2001-05-06"],
    "venue": "some stage",
    "venueCapacity": 50
}
###

###
#admin creates a zone for new event
POST http://localhost:8080/events/2/createZone
Content-Type: application/json
Authorization: Bearer 

{
    "zoneCapacity": 10,
    "zoneName": "testZonez",
    "zoneDate": "2001-05-06"
}
###

###
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
    "email": "liangzhejun@gmail.com",
    "password": "pw123",
    "dateOfBirth": "2001-06-23",
    "phoneNumber": "+6582887066"

}
###

###
#user sign up, valid password.
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
    "email": "liangzhejun@gmail.com",
    "password": "Password123!",
    "dateOfBirth": "2001-06-23",
    "phoneNumber": "+6582887066"

}
###

###
#user try to sign in, without validating OTP first.
POST http://localhost:8080/auth/signin
Content-Type: application/json

{
    "email": "liangzhejun@gmail.com",
    "password": "Password123!"
}
###

###
#user key in wrong OTP
POST http://localhost:8080/otp/validate
Content-Type: application/json

{
    "email":"liangzhejun@gmail.com",
    "otpNumber":"0000"
}
###

###
#user can request re-send of OTP
POST http://localhost:8080/otp/send
Content-Type: application/json

{
    "email":"liangzhejun@gmail.com",
    "phoneNumber": "+6582887066"
}
###

###
#user key in right OTP
POST http://localhost:8080/otp/validate
Content-Type: application/json

{
    "email":"liangzhejun@gmail.com",
    "otpNumber":"596134"
}
###

###
#user try to sign in, with wrong credientials.
POST http://localhost:8080/auth/signin
Content-Type: application/json

{
    "email": "liangzhejun@gmail.com",
    "password": "pw123"
}
###

###
#user try to sign in, with right credientials, returns a JWT token required to access other items.
POST http://localhost:8080/auth/signin
Content-Type: application/json

{
    "email": "liangzhejun@gmail.com",
    "password": "Password123!"
}
###

###
#user view available events
GET http://localhost:8080/events
Content-Type: application/json
Authorization: Bearer 

###

###
###
#user view existing zones in an event
GET http://localhost:8080/events/1/zones
Content-Type: application/json
Authorization: Bearer 

###

###
#user tries to pre-register for a zone when it hasn't been opened.
PUT http://localhost:8080/events/1/zone=1/preRegister
Content-Type: application/json
Authorization: Bearer 

###

###
#admin opens the pre-registration for an event.
PUT http://localhost:8080/events/1/open
Content-Type: application/json
Authorization: Bearer 

###

###
#user tries to pre-register for a zone when after it has opened.
PUT http://localhost:8080/events/1/testZone/preRegister
Content-Type: application/json
Authorization: Bearer 

###

###
#user tries to pre-register for another zone when they already joined one, for the same event.
PUT http://localhost:8080/events/1/testZone2/preRegister
Content-Type: application/json
Authorization: Bearer 

###

###
#admin tries to open the pre-registration for the other event.
PUT http://localhost:8080/events/2/open
Content-Type: application/json
Authorization: Bearer 

###

###
#user tries to pre-register for a zone in another event while pre registered for another. 
PUT http://localhost:8080/events/2/testZonez/preRegister
Content-Type: application/json
Authorization: Bearer 

###







#####################################################################################################################################

###
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
    "email": "liangzhejun@gmail.com",
    "password": "pw123",
    "dateOfBirth": "2001-06-23",
    "phoneNumber": "+6582887066"

}
###

###
#user sign up, valid password.
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
    "email": "liangzhejun@gmail.com",
    "password": "Password123!",
    "dateOfBirth": "2001-06-23",
    "phoneNumber": "+6582887066"

}
###

###
#user try to sign in, without validating OTP first.
POST http://localhost:8080/auth/signin
Content-Type: application/json

{
    "email": "liangzhejun@gmail.com",
    "password": "Password123!"
}
###

###
#user key in wrong OTP
POST http://localhost:8080/otp/validate
Content-Type: application/json

{
    "email":"liangzhejun@gmail.com",
    "otpNumber":"0000"
}
###

###
#user can request re-send of OTP
POST http://localhost:8080/otp/send
Content-Type: application/json

{
    "email":"liangzhejun@gmail.com",
    "phoneNumber": "+6582887066"
}
###

###
#user key in right OTP
POST http://localhost:8080/otp/validate
Content-Type: application/json

{
    "email":"liangzhejun@gmail.com",
    "otpNumber":"968806"
}
###

###
#user try to sign in, with wrong credientials.
POST http://localhost:8080/auth/signin
Content-Type: application/json

{
    "email": "liangzhejun@gmail.com",
    "password": "pw123"
}
###

###
#user try to sign in, with right credientials, returns a JWT token required to access other items.
POST http://localhost:8080/auth/signin
Content-Type: application/json

{
    "email": "liangzhejun@gmail.com",
    "password": "Password123!"
}
###

###
#user view events
GET http://localhost:8080/events
Content-Type: application/json
Authorization: Bearer 
###


###
#user tries to create an event (403)
POST http://localhost:8080/events/create
Content-Type: application/json
Authorization: Bearer 

{
    "eventName": "concert",
    "artists": ["people", "more people"],
    "dates": ["2001-05-06"],
    "venue": "some stage",
    "venueCapacity": 50
}
###


###
#admin tries to create an event
POST http://localhost:8080/events/create
Content-Type: application/json
Authorization: Bearer 

{
    "eventName": "concert",
    "artists": ["people", "more people"],
    "dates": ["2001-05-06"],
    "venue": "some stage",
    "venueCapacity": 50
}
###

###
#user view events (can see that is has been created)
GET http://localhost:8080/events
Content-Type: application/json
Authorization: Bearer 
###

###
#user view existing zones in an event
GET http://localhost:8080/events/1/zones
Content-Type: application/json
Authorization: Bearer 
###

###
#user tries to create a zone
POST http://localhost:8080/events/1/createZone
Content-Type: application/json
Authorization: Bearer

{
    "zoneCapacity": 5,
    "zoneName": "testZone"
}
###

###
#admin tries to create a zone
POST http://localhost:8080/events/1/createZone
Content-Type: application/json
Authorization: Bearer 

{
    "zoneCapacity": 5,
    "zoneName": "testZone"
}
###

###
#user view existing zones in an event (show that it has been created)
GET http://localhost:8080/events/1/zones
Content-Type: application/json
Authorization: Bearer
###

###
#user tries to pre-register for a zone when it hasn't been opened.
PUT http://localhost:8080/events/1/testZone/preRegister
Content-Type: application/json
Authorization: Bearer

###

###
#user tries to open the pre-registration for an event. (403)
PUT http://localhost:8080/events/1/open
Content-Type: application/json
Authorization: Bearer 

###

###
#user tries to close the pre-registration for an event.
PUT http://localhost:8080/events/1/close
Content-Type: application/json
Authorization: Bearer 

###


###
#admin tries to close the pre-registration for an event.
PUT http://localhost:8080/events/1/close
Content-Type: application/json
Authorization: Bearer 

###


###
#admin tries to open the pre-registration for an event.
PUT http://localhost:8080/events/1/open
Content-Type: application/json
Authorization: Bearer 

###

###
#user tries to pre-register for a zone when after it has been opened.
PUT http://localhost:8080/events/1/testZone/preRegister
Content-Type: application/json
Authorization: Bearer 

###

###
#admin creates another zone
POST http://localhost:8080/events/1/createZone
Content-Type: application/json
Authorization: Bearer 

{
    "zoneCapacity": 10,
    "zoneName": "testZone2"
}
###

###
#see all existing zones
GET http://localhost:8080/events/1/zones
Content-Type: application/json
Authorization: Bearer 

###
#user tries to pre-register for another zone when they already joined one, for the same event.
PUT http://localhost:8080/events/1/testZone2/preRegister
Content-Type: application/json
Authorization: Bearer 
###

###
#admin creates another event
POST http://localhost:8080/events/create
Content-Type: application/json
Authorization: Bearer 

{
    "eventName": "concert2",
    "artists": ["people", "more people"],
    "dates": ["2001-05-06"],
    "venue": "some stage",
    "venueCapacity": 50
}
###

###
#admin creates a zone for new event
POST http://localhost:8080/events/2/createZone
Content-Type: application/json
Authorization: Bearer 

{
    "zoneCapacity": 10,
    "zoneName": "testZonez"
}
###

###
#user view events (can see that is has been created)
GET http://localhost:8080/events
Content-Type: application/json
Authorization: Bearer 
###

###
#admin tries to open the pre-registration for the event.
PUT http://localhost:8080/events/2/open
Content-Type: application/json
Authorization: Bearer 

###

###
#user tries to pre-register for a zone when after it has been opened.
PUT http://localhost:8080/events/2/testZonez/preRegister
Content-Type: application/json
Authorization: Bearer 

###


###
#admin view all users who have signed up
GET http://localhost:8080/users/all
Content-Type: application/json
Authorization: Bearer

###

