# REST test cases for tickets

###
GET http://localhost:8080/tickets

### ([PROBLEM] TicketNotFound error messgaes not showing up)
GET http://localhost:8080/tickets/2


###
POST http://localhost:8080/tickets
Content-Type: application/json

{
    "ticketPrice": 3000
}

### ([PROBLEM] TicketNotFound error messgaes not showing up)
PUT http://localhost:8080/tickets/2
Content-Type: application/json

{
    "ticketPrice": 6969
}

###
DELETE http://localhost:8080/tickets/2



#USER TEST
GET http://localhost:8080/users


###
GET http://localhost:8080/users/3

###
GET http://localhost:8080/users/blank@gmail.com

###
DELETE http://localhost:8080/users/blank@gmail.com


###
POST http://localhost:8080/users
Content-Type: application/json

{
    "email": "blank@gmail.com",
    "age": "18",
    "phoneNum": "1231231291",
    "password": "lel"
}

###
PUT http://localhost:8080/users/blal@gmail.com
Content-Type: application/json

{
    "email": "blal@gmail.com",
    "age": "14",
    "phoneNum": "01234567891",
    "password": "ok"
}
